 name:
  Daily YNAB Chron Jobs
 on:
  schedule:
    - cron: "0 14,21 * * *"
 jobs:
  ynit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install YNIT
        run: npm install ynab_investment_tracking
      - name: Run YNIT
        shell: bash
        env:
          YNAB_API_TOKEN: ${{ secrets.YNAB_API_TOKEN }}
          YNAB_BUDGET_ID: ${{ secrets.YNAB_BUDGET_ID }}
        run: cd node_modules/ynab_investment_tracking && npm run start
        
