 name:
  Daily YNAB Chron Jobs
 on:
  schedule:
    - cron: "*/5 * * * *"
 jobs:
  ynit:
    runs-on: ubuntu-latest
    steps:
      - name: Run YNIT
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - shell: bash
        env:
          YNAB_API_TOKEN: ${{ secrets.YNAB_API_TOKEN }}
          YNAB_BUDGET_ID: ${{ secrets.YNAB_BUDGET_ID }}
      - run: npm install ynab_investment_tracking
      - run: cd node_modules/ynab_investment_tracking
      - run: npm run start
        
